update prototools

diff --git a/bin/update-deps b/bin/update-deps
--- a/bin/update-deps
+++ b/bin/update-deps
@@ -7,21 +7,21 @@ echo ""
 STEP=0
 
 function run_step() {
-	STEP=$((STEP + 1))
-	echo "[$STEP] - $1..."
+  STEP=$((STEP + 1))
+  echo "[$STEP] - $1..."
 
-	local start=$(date +%s)
-	$2
-	if [ $? -eq 0 ]; then
-		local end=$(date +%s)
-		local runtime=$((end - start))
+  local start=$(date +%s)
+  $2
+  if [ $? -eq 0 ]; then
+    local end=$(date +%s)
+    local runtime=$((end - start))
 
-		echo "[$STEP] - $1...done in $runtime sec"
-		echo ""
-	else
-		echo "[$STEP] - $1...failed"
-		exit 1
-	fi
+    echo "[$STEP] - $1...done in $runtime sec"
+    echo ""
+  else
+    echo "[$STEP] - $1...failed"
+    exit 1
+  fi
 }
 
 # brew
@@ -31,9 +31,10 @@ run_step "brew upgrade" "brew upgrade"
 
 # proto toolchain
 if command -v proto >/dev/null; then
-	run_step "proto upgrade" "proto upgrade"
+  run_step "proto upgrade" "proto upgrade"
+  run_step "proto install" "proto install"
 else
-	echo "proto not installed, skipping..."
+  echo "proto not installed, skipping..."
 fi
 
 # tmux
