config updates

diff --git a/bin/update-deps b/bin/update-deps
--- a/bin/update-deps
+++ b/bin/update-deps
@@ -1,28 +1,27 @@
 #!/usr/bin/env bash
 
-
-start=`date +%s`
+start=$(date +%s)
 echo "Updating dependencies..."
 echo ""
 
 STEP=0
 
 function run_step() {
-  STEP=$((STEP+1))
-  echo "[$STEP] - $1..."
+	STEP=$((STEP + 1))
+	echo "[$STEP] - $1..."
 
-  local start=`date +%s`
-  $2
-  if [ $? -eq 0 ]; then
-    local end=`date +%s`
-    local runtime=$((end-start))
+	local start=$(date +%s)
+	$2
+	if [ $? -eq 0 ]; then
+		local end=$(date +%s)
+		local runtime=$((end - start))
 
-    echo "[$STEP] - $1...done in $runtime sec"
-    echo ""
-  else
-    echo "[$STEP] - $1...failed"
-    exit 1
-  fi
+		echo "[$STEP] - $1...done in $runtime sec"
+		echo ""
+	else
+		echo "[$STEP] - $1...failed"
+		exit 1
+	fi
 }
 
 # brew
@@ -30,24 +29,17 @@ run_step "install brew bundle" "brew bundle install"
 run_step "brew update" "brew update"
 run_step "brew upgrade" "brew upgrade"
 
+# proto toolchain
+if command -v proto >/dev/null; then
+	run_step "proto upgrade" "proto upgrade"
+else
+	echo "proto not installed, skipping..."
+fi
+
 # tmux
 run_step "clanup tmux plugins" "$HOME/.tmux/plugins/tpm/bin/clean_plugins"
 run_step "update tmux plugins" "$HOME/.tmux/plugins/tpm/bin/update_plugins all"
 
-# bun
-if command -v bun > /dev/null; then
-  run_step "upgrade bun" "bun upgrade"
-else
-  echo "bun not installed, skipping..."
-fi
-
-# deno
-if command -v deno > /dev/null; then
-  run_step "upgrade deno" "deno upgrade"
-else
-  echo "deno not installed, skipping..."
-fi
-
-end=`date +%s`
-runtime=$((end-start))
+end=$(date +%s)
+runtime=$((end - start))
 echo "Done in $runtime sec"
